# Generated by Django 3.2.5 on 2021-08-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='storeuser',
            managers=[
            ],
        ),
    ]
