# Generated by Django 3.2.5 on 2021-07-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
