# Generated by Django 3.2.5 on 2021-08-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0002_alter_storeuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='email',
            field=models.EmailField(max_length=25, unique=True),
        ),
    ]
