# Generated by Django 3.2.5 on 2021-08-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0003_auto_20210728_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='email',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
