# Generated by Django 3.2.5 on 2021-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0004_auto_20210804_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='url',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
