# Generated by Django 3.2.5 on 2021-08-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0005_storeuser_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeuser',
            name='url',
        ),
    ]
