version: '3.9'

services:
  db:
    container_name: store_app_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: store_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf

    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
