version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db



#version: '3.9'
#
#services:
#    web:
#        build: .
#        command: python /store_app/store_app/manage.py runserver 0.0.0.0:8000
#        ports:
#            - 8000:8000
#        depends_on:
#          - db
#    db:
#      image: postgres




#services:
#  store_db:
#    container_name: django_exam
#    image: store_app
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_PASSWORD: asdf
#      POSTGRES_USER: postgres
#      POSTGRES_DB: store_db
#    volumes:
#      - ./postgresql/data:/var/lib/postgresql/data
