version: '3.9'

services:
  postgres:
    container_name: store_app_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf1234

    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    build:
      context: .
      dockerfile: Dockerfile
