# Generated by Django 3.2.5 on 2021-07-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
            ],
        ),
    ]
