# Generated by Django 3.2.5 on 2021-08-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('category', models.BooleanField(choices=[(1, 'Electronics'), (2, 'Furniture'), (3, 'Kids staff')])),
            ],
        ),
    ]
