# Generated by Django 3.2.5 on 2021-08-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210803_0400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
