# Generated by Django 3.2.5 on 2021-08-10 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
