# Generated by Django 3.2.5 on 2021-08-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
