# Generated by Django 3.2.5 on 2021-08-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.SlugField(unique=True),
        ),
    ]
