# Generated by Django 3.2.5 on 2021-08-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_products_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='profile',
            new_name='cart',
        ),
    ]
