# Generated by Django 3.2.5 on 2021-08-07 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0019_alter_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='profile',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_auth.storeuser'),
            preserve_default=False,
        ),
    ]
