# Generated by Django 3.2.5 on 2021-08-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210807_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
