# Generated by Django 3.2.5 on 2021-08-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
