# Generated by Django 3.2.5 on 2021-08-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_cart_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Profile',
        ),
    ]
