# Generated by Django 3.2.5 on 2021-08-07 22:13

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='budget',
            field=models.IntegerField(default=2000, verbose_name=django.db.models.fields.PositiveIntegerField),
            preserve_default=False,
        ),
    ]
