# Generated by Django 3.2.5 on 2021-08-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_cart_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='budget',
            new_name='cash',
        ),
    ]
